language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis.php.ini; fi;'
  - composer self-update
  - composer install --dev --no-interaction
  - mkdir -p build/logs

script: vendor/bin/phpunit --coverage-clover clover.xml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml
    
matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
  
