language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis.php.ini; fi;'
  - composer self-update
  - composer install --dev --no-interaction
  - mkdir -p build/logs

after_script:
  - php vendor/bin/coveralls -v

matrix:
  allow_failures:
    - php: hhvm
  fast_finish: true
