language: php

sudo: false

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_script:
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then phpenv config-add .travis.php.ini; fi;'
  - sh -c 'if [ "$TRAVIS_PHP_VERSION" = "5.5" ]; then sudo apt-get install php5-gmp; fi;'
  - composer self-update
  - composer install --dev --no-interaction

script: vendor/bin/phpunit --debug --coverage-clover clover.xml

after_success:
    - wget https://scrutinizer-ci.com/ocular.phar
    - php ocular.phar code-coverage:upload --format=php-clover clover.xml
    
matrix:
  allow_failures:
    - php: 5.4
    - php: 5.5
  fast_finish: true
  
